services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart:
      unless-stopped

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    expose:
      - 3306
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart:
      unless-stopped    
    healthcheck:
      test: mysqladmin ping --host=localhost -p${INCEPTION_MY_SQL_PASS}
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 5s

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart:
      unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy      

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/${INCEPTION_LOGIN}/data/wordpress"
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/${INCEPTION_LOGIN}/data/database"

networks:
  inception:
    name: inception
    driver: bridge